### ISSUE TITLE
MQTT join message not sending after Node JoinAccept

### ISSUE THREAD

**Issue by rayman18** [brocaar/lora-app-server#368]
### Is this a bug or a feature request?
Bug
### What did you expect?
MQTT join mesage published after node join. The MQTT join topic message should be published when JoinAccept occurs without waiting for the first uplink.
### What happened?
MQTT join message published after first uplink received from the node. 
### What version are your using?
v3.3.1
### How can your issue be reproduced?
Node OTAA Join

**Comment by brocaar** [comment]
This is intentional, and this aligns with the flow as described in the LoRaWAN Backend Interface specification.

A (re)join can only be confirmed when a device sends its first uplink. Note that for a LoRaWAN 1.1 re-join request, the device will continue to use the old security context when it does not receive the join-accept.
