### ISSUE TITLE
Application ID is increased even if parameters are invalid

### ISSUE THREAD

**Issue by jcourtat** [brocaar/lora-app-server#46]
in following POST message, channelListID is invalid:

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Grpc-Metadata-Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb3JhLWFwcC1zZXJ2ZXIiLCJhdWQiOiJsb3JhLWFwcC1zZXJ2ZXIiLCJuYmYiOjE0OTAxOTI5NjEsImV4cCI6MTQ5OTY1MzMwMCwic3ViIjoidXNlciIsInVzZXJuYW1lIjoianVsaWVuIn0.JdL95G69U_27fArOFKy0toLgqmpHMH3CucRaPYs4f_s' -d '{ \ 
   "adrInterval": 10, \ 
   "channelListID" : "800", \ 
   "description": "this application has color blue", \ 
   "installationMargin": 2, \ 
   "isABP": true, \ 
   "isClassC": false, \ 
   "name": "sensor-blue", \ 
   "relaxFCnt": true, \ 
   "rx1DROffset": 0, \ 
   "rx2DR": 0, \ 
   "rxDelay": 10, \ 
   "rxWindow": "RX1" \ 
 }' 'https://localhost:8080/api/applications'

If you repeat the HTTP request a couple of times then you fix the request, the Application ID is increased by the number of invalid tries.
I don't know yet how the FPort and the application id are linked, but maybe it could break something

**Comment by brocaar** [comment]
Nothing to worry about. LoRa App Server tries to insert but PostgreSQL rejects it because of the invalid channel-list id (foreign key constraint error). Because of the attempt, the ID sequence is increased which is normal behaviour for a db as it is the only way to handle concurrent inserts. There is no relation with the `FPort`. Again, nothing to worry about. 😄
